#!/usr/bin/env node
/**
 * Omnicraft migration - generates import.sql and validate.sql from manifest.json.
 * Re-run after any schema change:  node scripts/migration/generate-sql.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(readFileSync(join(here, "manifest.json"), "utf8"));

/** Hard foreign keys enforced by the database (child.col -> parent(col)). */
const FK = {
  profiles: [["id", "auth.users", "id"]],
  user_roles: [["user_id", "auth.users", "id"]],
  creator_specialties: [["user_id", "auth.users", "id"]],
  conversations: [["created_by", "auth.users", "id"]],
  conversation_members: [
    ["conversation_id", "public.conversations", "id"],
    ["user_id", "auth.users", "id"],
  ],
  squads: [["conversation_id", "public.conversations", "id"]],
  squad_members: [["squad_id", "public.squads", "id"]],
  squad_invites: [["squad_id", "public.squads", "id"]],
  squad_join_requests: [["squad_id", "public.squads", "id"]],
  job_applications: [
    ["job_id", "public.jobs", "id"],
    ["squad_id", "public.squads", "id"],
  ],
  posts: [["author_id", "auth.users", "id"]],
  stories: [["user_id", "auth.users", "id"]],
  story_views: [
    ["story_id", "public.stories", "id"],
    ["viewer_id", "auth.users", "id"],
  ],
  messages: [
    ["conversation_id", "public.conversations", "id"],
    ["sender_id", "auth.users", "id"],
  ],
  message_reactions: [
    ["message_id", "public.messages", "id"],
    ["user_id", "auth.users", "id"],
  ],
  typing_status: [
    ["conversation_id", "public.conversations", "id"],
    ["user_id", "auth.users", "id"],
  ],
};

/** Self-referencing columns: nulled on insert, back-filled afterwards. */
const SELF_REF = { messages: ["reply_to", "id"] };

const head = `-- =====================================================================
-- Omnicraft :: DATA IMPORT  (generated by scripts/migration/generate-sql.mjs)
--
-- Run AFTER the schema exists and AFTER auth users are imported:
--   psql "$TARGET_DB_URL" -v ON_ERROR_STOP=1 -f scripts/migration/import.sql
--
-- Must be run from the directory holding ./migration-data/*.csv
-- Idempotent: safe to re-run; existing rows are skipped, never duplicated.
-- =====================================================================
\\set ON_ERROR_STOP on
BEGIN;

CREATE TABLE IF NOT EXISTS public._migration_report (
  table_name       text PRIMARY KEY,
  csv_rows         integer NOT NULL,
  importable_rows  integer NOT NULL,
  inserted         integer NOT NULL,
  skipped_orphan   integer NOT NULL,
  skipped_conflict integer NOT NULL,
  run_at           timestamptz NOT NULL DEFAULT now()
);
TRUNCATE public._migration_report;

-- Triggers would re-fire notifications for historical rows and rewrite
-- timestamps, so they stay off for the duration of the load.
SET session_replication_role = replica;
`;

let sql = head;

for (const { name, userRefs } of manifest.tables) {
  const fks = FK[name] ?? [];
  const self = SELF_REF[name];
  const guards = fks
    .filter(([col]) => !(self && col === self[0]))
    .map(
      ([col, parent, pcol]) =>
        `    (s.${col} IS NULL OR EXISTS (SELECT 1 FROM ${parent} p WHERE p.${pcol} = s.${col}))`,
    );
  const where = guards.length ? `\n  WHERE\n${guards.join("\n    AND\n")}` : "";

  sql += `
-- ---------------------------------------------------------------- ${name}
CREATE TEMP TABLE stg_${name} (LIKE public.${name} INCLUDING DEFAULTS) ON COMMIT DROP;
\\copy stg_${name} FROM 'migration-data/${name}.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_${name} ON COMMIT DROP AS
  SELECT s.* FROM stg_${name} s${where};
`;

  if (self) {
    sql += `UPDATE ok_${name} SET ${self[0]} = NULL;  -- self-reference restored below\n`;
  }

  sql += `
WITH ins AS (
  INSERT INTO public.${name} SELECT * FROM ok_${name} ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT '${name}',
       (SELECT count(*) FROM stg_${name}),
       (SELECT count(*) FROM ok_${name}),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_${name}) - (SELECT count(*) FROM ok_${name}),
       (SELECT count(*) FROM ok_${name}) - (SELECT count(*) FROM ins);
`;

  if (self) {
    sql += `
-- restore ${name}.${self[0]} now that all rows exist
UPDATE public.${name} t
   SET ${self[0]} = s.${self[0]}
  FROM stg_${name} s
 WHERE t.id = s.id
   AND s.${self[0]} IS NOT NULL
   AND EXISTS (SELECT 1 FROM public.${name} p WHERE p.id = s.${self[0]});
`;
  }

  if (userRefs?.length) {
    sql += `
-- soft check: ${name} rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT '${name}', c.col, c.n FROM (
${userRefs
  .map(
    (c) =>
      `  SELECT '${c}'::text AS col, count(*)::int AS n FROM public.${name} x
    WHERE x.${c} IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.${c})`,
  )
  .join("\n  UNION ALL\n")}
) c WHERE c.n > 0;
`;
  }
}

sql += `
SET session_replication_role = origin;
COMMIT;

\\echo ''
\\echo '=== IMPORT REPORT ==='
SELECT table_name, csv_rows, inserted, skipped_orphan, skipped_conflict
  FROM public._migration_report ORDER BY table_name;
\\echo ''
\\echo '=== DANGLING USER REFERENCES (expected > 0 only if you skipped auth import) ==='
SELECT * FROM public._migration_orphans ORDER BY table_name, column_name;
`;

// _migration_orphans must exist before the first insert into it.
sql = sql.replace(
  "TRUNCATE public._migration_report;",
  `TRUNCATE public._migration_report;

CREATE TABLE IF NOT EXISTS public._migration_orphans (
  table_name    text NOT NULL,
  column_name   text NOT NULL,
  missing_count integer NOT NULL
);
TRUNCATE public._migration_orphans;`,
);

writeFileSync(join(here, "import.sql"), sql);

// ---------------------------------------------------------------- validate
const rows = manifest.tables
  .map((t) => `  SELECT '${t.name}'::text AS table_name, count(*)::int AS target_rows FROM public.${t.name}`)
  .join("\n  UNION ALL\n");

writeFileSync(
  join(here, "validate.sql"),
  `-- =====================================================================
-- Omnicraft :: POST-IMPORT VALIDATION
--   psql "$TARGET_DB_URL" -f scripts/migration/validate.sql
-- Run from the directory holding ./migration-data/_counts.csv
-- =====================================================================
CREATE TEMP TABLE src_counts (table_name text, row_count int);
\\copy src_counts FROM 'migration-data/_counts.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE tgt_counts AS
${rows};

\\echo ''
\\echo '=== ROW COUNT COMPARISON (source vs target) ==='
SELECT s.table_name,
       s.row_count AS source_rows,
       t.target_rows,
       t.target_rows - s.row_count AS diff,
       CASE WHEN t.target_rows = s.row_count THEN 'OK' ELSE 'MISMATCH' END AS status
  FROM src_counts s
  JOIN tgt_counts t USING (table_name)
 ORDER BY status DESC, s.table_name;

\\echo ''
\\echo '=== SUMMARY ==='
SELECT count(*) FILTER (WHERE t.target_rows = s.row_count) AS tables_ok,
       count(*) FILTER (WHERE t.target_rows <> s.row_count) AS tables_mismatched,
       sum(s.row_count) AS source_total,
       sum(t.target_rows) AS target_total
  FROM src_counts s JOIN tgt_counts t USING (table_name);

\\echo ''
\\echo '=== AUTH COVERAGE ==='
SELECT (SELECT count(*) FROM auth.users) AS auth_users,
       (SELECT count(*) FROM public.profiles) AS profiles,
       (SELECT count(*) FROM public.profiles p
         WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = p.id)) AS profiles_without_auth_user;

\\echo ''
\\echo '=== REFERENTIAL INTEGRITY SPOT CHECKS ==='
SELECT 'follows -> profiles' AS check, count(*) AS broken FROM public.follows f
  WHERE NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = f.follower_id)
     OR NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = f.following_id)
UNION ALL SELECT 'posts -> profiles', count(*) FROM public.posts x
  WHERE NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = x.author_id)
UNION ALL SELECT 'post_likes -> posts', count(*) FROM public.post_likes x
  WHERE NOT EXISTS (SELECT 1 FROM public.posts p WHERE p.id = x.post_id)
UNION ALL SELECT 'post_comments -> posts', count(*) FROM public.post_comments x
  WHERE NOT EXISTS (SELECT 1 FROM public.posts p WHERE p.id = x.post_id)
UNION ALL SELECT 'job_applications -> jobs', count(*) FROM public.job_applications x
  WHERE NOT EXISTS (SELECT 1 FROM public.jobs j WHERE j.id = x.job_id)
UNION ALL SELECT 'squad_members -> squads', count(*) FROM public.squad_members x
  WHERE NOT EXISTS (SELECT 1 FROM public.squads s WHERE s.id = x.squad_id)
UNION ALL SELECT 'messages -> conversations', count(*) FROM public.messages x
  WHERE NOT EXISTS (SELECT 1 FROM public.conversations c WHERE c.id = x.conversation_id)
UNION ALL SELECT 'portfolios -> profiles', count(*) FROM public.portfolios x
  WHERE NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = x.user_id);
`,
);

console.log("wrote import.sql and validate.sql");
