-- =====================================================================
-- Omnicraft :: DATA IMPORT  (generated by scripts/migration/generate-sql.mjs)
--
-- Run AFTER the schema exists and AFTER auth users are imported:
--   psql "$TARGET_DB_URL" -v ON_ERROR_STOP=1 -f scripts/migration/import.sql
--
-- Must be run from the directory holding ./migration-data/*.csv
-- Idempotent: safe to re-run; existing rows are skipped, never duplicated.
-- =====================================================================
\set ON_ERROR_STOP on
BEGIN;

CREATE TABLE IF NOT EXISTS public._migration_report (
  table_name       text PRIMARY KEY,
  csv_rows         integer NOT NULL,
  importable_rows  integer NOT NULL,
  inserted         integer NOT NULL,
  skipped_orphan   integer NOT NULL,
  skipped_conflict integer NOT NULL,
  run_at           timestamptz NOT NULL DEFAULT now()
);
TRUNCATE public._migration_report;

CREATE TABLE IF NOT EXISTS public._migration_orphans (
  table_name    text NOT NULL,
  column_name   text NOT NULL,
  missing_count integer NOT NULL
);
TRUNCATE public._migration_orphans;

-- Triggers would re-fire notifications for historical rows and rewrite
-- timestamps, so they stay off for the duration of the load.
SET session_replication_role = replica;

-- ---------------------------------------------------------------- profiles
CREATE TEMP TABLE stg_profiles (LIKE public.profiles INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_profiles FROM 'migration-data/profiles.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_profiles ON COMMIT DROP AS
  SELECT s.* FROM stg_profiles s
  WHERE
    (s.id IS NULL OR EXISTS (SELECT 1 FROM auth.users p WHERE p.id = s.id));

WITH ins AS (
  INSERT INTO public.profiles SELECT * FROM ok_profiles ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'profiles',
       (SELECT count(*) FROM stg_profiles),
       (SELECT count(*) FROM ok_profiles),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_profiles) - (SELECT count(*) FROM ok_profiles),
       (SELECT count(*) FROM ok_profiles) - (SELECT count(*) FROM ins);

-- soft check: profiles rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'profiles', c.col, c.n FROM (
  SELECT 'id'::text AS col, count(*)::int AS n FROM public.profiles x
    WHERE x.id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- profile_contacts
CREATE TEMP TABLE stg_profile_contacts (LIKE public.profile_contacts INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_profile_contacts FROM 'migration-data/profile_contacts.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_profile_contacts ON COMMIT DROP AS
  SELECT s.* FROM stg_profile_contacts s;

WITH ins AS (
  INSERT INTO public.profile_contacts SELECT * FROM ok_profile_contacts ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'profile_contacts',
       (SELECT count(*) FROM stg_profile_contacts),
       (SELECT count(*) FROM ok_profile_contacts),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_profile_contacts) - (SELECT count(*) FROM ok_profile_contacts),
       (SELECT count(*) FROM ok_profile_contacts) - (SELECT count(*) FROM ins);

-- soft check: profile_contacts rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'profile_contacts', c.col, c.n FROM (
  SELECT 'id'::text AS col, count(*)::int AS n FROM public.profile_contacts x
    WHERE x.id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- user_roles
CREATE TEMP TABLE stg_user_roles (LIKE public.user_roles INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_user_roles FROM 'migration-data/user_roles.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_user_roles ON COMMIT DROP AS
  SELECT s.* FROM stg_user_roles s
  WHERE
    (s.user_id IS NULL OR EXISTS (SELECT 1 FROM auth.users p WHERE p.id = s.user_id));

WITH ins AS (
  INSERT INTO public.user_roles SELECT * FROM ok_user_roles ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'user_roles',
       (SELECT count(*) FROM stg_user_roles),
       (SELECT count(*) FROM ok_user_roles),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_user_roles) - (SELECT count(*) FROM ok_user_roles),
       (SELECT count(*) FROM ok_user_roles) - (SELECT count(*) FROM ins);

-- soft check: user_roles rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'user_roles', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.user_roles x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- creator_specialties
CREATE TEMP TABLE stg_creator_specialties (LIKE public.creator_specialties INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_creator_specialties FROM 'migration-data/creator_specialties.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_creator_specialties ON COMMIT DROP AS
  SELECT s.* FROM stg_creator_specialties s
  WHERE
    (s.user_id IS NULL OR EXISTS (SELECT 1 FROM auth.users p WHERE p.id = s.user_id));

WITH ins AS (
  INSERT INTO public.creator_specialties SELECT * FROM ok_creator_specialties ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'creator_specialties',
       (SELECT count(*) FROM stg_creator_specialties),
       (SELECT count(*) FROM ok_creator_specialties),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_creator_specialties) - (SELECT count(*) FROM ok_creator_specialties),
       (SELECT count(*) FROM ok_creator_specialties) - (SELECT count(*) FROM ins);

-- soft check: creator_specialties rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'creator_specialties', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.creator_specialties x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- follows
CREATE TEMP TABLE stg_follows (LIKE public.follows INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_follows FROM 'migration-data/follows.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_follows ON COMMIT DROP AS
  SELECT s.* FROM stg_follows s;

WITH ins AS (
  INSERT INTO public.follows SELECT * FROM ok_follows ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'follows',
       (SELECT count(*) FROM stg_follows),
       (SELECT count(*) FROM ok_follows),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_follows) - (SELECT count(*) FROM ok_follows),
       (SELECT count(*) FROM ok_follows) - (SELECT count(*) FROM ins);

-- soft check: follows rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'follows', c.col, c.n FROM (
  SELECT 'follower_id'::text AS col, count(*)::int AS n FROM public.follows x
    WHERE x.follower_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.follower_id)
  UNION ALL
  SELECT 'following_id'::text AS col, count(*)::int AS n FROM public.follows x
    WHERE x.following_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.following_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- conversations
CREATE TEMP TABLE stg_conversations (LIKE public.conversations INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_conversations FROM 'migration-data/conversations.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_conversations ON COMMIT DROP AS
  SELECT s.* FROM stg_conversations s
  WHERE
    (s.created_by IS NULL OR EXISTS (SELECT 1 FROM auth.users p WHERE p.id = s.created_by));

WITH ins AS (
  INSERT INTO public.conversations SELECT * FROM ok_conversations ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'conversations',
       (SELECT count(*) FROM stg_conversations),
       (SELECT count(*) FROM ok_conversations),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_conversations) - (SELECT count(*) FROM ok_conversations),
       (SELECT count(*) FROM ok_conversations) - (SELECT count(*) FROM ins);

-- soft check: conversations rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'conversations', c.col, c.n FROM (
  SELECT 'created_by'::text AS col, count(*)::int AS n FROM public.conversations x
    WHERE x.created_by IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.created_by)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- conversation_members
CREATE TEMP TABLE stg_conversation_members (LIKE public.conversation_members INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_conversation_members FROM 'migration-data/conversation_members.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_conversation_members ON COMMIT DROP AS
  SELECT s.* FROM stg_conversation_members s
  WHERE
    (s.conversation_id IS NULL OR EXISTS (SELECT 1 FROM public.conversations p WHERE p.id = s.conversation_id))
    AND
    (s.user_id IS NULL OR EXISTS (SELECT 1 FROM auth.users p WHERE p.id = s.user_id));

WITH ins AS (
  INSERT INTO public.conversation_members SELECT * FROM ok_conversation_members ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'conversation_members',
       (SELECT count(*) FROM stg_conversation_members),
       (SELECT count(*) FROM ok_conversation_members),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_conversation_members) - (SELECT count(*) FROM ok_conversation_members),
       (SELECT count(*) FROM ok_conversation_members) - (SELECT count(*) FROM ins);

-- soft check: conversation_members rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'conversation_members', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.conversation_members x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- squads
CREATE TEMP TABLE stg_squads (LIKE public.squads INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_squads FROM 'migration-data/squads.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_squads ON COMMIT DROP AS
  SELECT s.* FROM stg_squads s
  WHERE
    (s.conversation_id IS NULL OR EXISTS (SELECT 1 FROM public.conversations p WHERE p.id = s.conversation_id));

WITH ins AS (
  INSERT INTO public.squads SELECT * FROM ok_squads ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'squads',
       (SELECT count(*) FROM stg_squads),
       (SELECT count(*) FROM ok_squads),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_squads) - (SELECT count(*) FROM ok_squads),
       (SELECT count(*) FROM ok_squads) - (SELECT count(*) FROM ins);

-- soft check: squads rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'squads', c.col, c.n FROM (
  SELECT 'owner_id'::text AS col, count(*)::int AS n FROM public.squads x
    WHERE x.owner_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.owner_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- squad_members
CREATE TEMP TABLE stg_squad_members (LIKE public.squad_members INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_squad_members FROM 'migration-data/squad_members.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_squad_members ON COMMIT DROP AS
  SELECT s.* FROM stg_squad_members s
  WHERE
    (s.squad_id IS NULL OR EXISTS (SELECT 1 FROM public.squads p WHERE p.id = s.squad_id));

WITH ins AS (
  INSERT INTO public.squad_members SELECT * FROM ok_squad_members ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'squad_members',
       (SELECT count(*) FROM stg_squad_members),
       (SELECT count(*) FROM ok_squad_members),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_squad_members) - (SELECT count(*) FROM ok_squad_members),
       (SELECT count(*) FROM ok_squad_members) - (SELECT count(*) FROM ins);

-- soft check: squad_members rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'squad_members', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.squad_members x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- squad_invites
CREATE TEMP TABLE stg_squad_invites (LIKE public.squad_invites INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_squad_invites FROM 'migration-data/squad_invites.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_squad_invites ON COMMIT DROP AS
  SELECT s.* FROM stg_squad_invites s
  WHERE
    (s.squad_id IS NULL OR EXISTS (SELECT 1 FROM public.squads p WHERE p.id = s.squad_id));

WITH ins AS (
  INSERT INTO public.squad_invites SELECT * FROM ok_squad_invites ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'squad_invites',
       (SELECT count(*) FROM stg_squad_invites),
       (SELECT count(*) FROM ok_squad_invites),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_squad_invites) - (SELECT count(*) FROM ok_squad_invites),
       (SELECT count(*) FROM ok_squad_invites) - (SELECT count(*) FROM ins);

-- soft check: squad_invites rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'squad_invites', c.col, c.n FROM (
  SELECT 'inviter_id'::text AS col, count(*)::int AS n FROM public.squad_invites x
    WHERE x.inviter_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.inviter_id)
  UNION ALL
  SELECT 'invitee_id'::text AS col, count(*)::int AS n FROM public.squad_invites x
    WHERE x.invitee_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.invitee_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- squad_join_requests
CREATE TEMP TABLE stg_squad_join_requests (LIKE public.squad_join_requests INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_squad_join_requests FROM 'migration-data/squad_join_requests.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_squad_join_requests ON COMMIT DROP AS
  SELECT s.* FROM stg_squad_join_requests s
  WHERE
    (s.squad_id IS NULL OR EXISTS (SELECT 1 FROM public.squads p WHERE p.id = s.squad_id));

WITH ins AS (
  INSERT INTO public.squad_join_requests SELECT * FROM ok_squad_join_requests ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'squad_join_requests',
       (SELECT count(*) FROM stg_squad_join_requests),
       (SELECT count(*) FROM ok_squad_join_requests),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_squad_join_requests) - (SELECT count(*) FROM ok_squad_join_requests),
       (SELECT count(*) FROM ok_squad_join_requests) - (SELECT count(*) FROM ins);

-- soft check: squad_join_requests rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'squad_join_requests', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.squad_join_requests x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- jobs
CREATE TEMP TABLE stg_jobs (LIKE public.jobs INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_jobs FROM 'migration-data/jobs.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_jobs ON COMMIT DROP AS
  SELECT s.* FROM stg_jobs s;

WITH ins AS (
  INSERT INTO public.jobs SELECT * FROM ok_jobs ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'jobs',
       (SELECT count(*) FROM stg_jobs),
       (SELECT count(*) FROM ok_jobs),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_jobs) - (SELECT count(*) FROM ok_jobs),
       (SELECT count(*) FROM ok_jobs) - (SELECT count(*) FROM ins);

-- soft check: jobs rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'jobs', c.col, c.n FROM (
  SELECT 'client_id'::text AS col, count(*)::int AS n FROM public.jobs x
    WHERE x.client_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.client_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- job_applications
CREATE TEMP TABLE stg_job_applications (LIKE public.job_applications INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_job_applications FROM 'migration-data/job_applications.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_job_applications ON COMMIT DROP AS
  SELECT s.* FROM stg_job_applications s
  WHERE
    (s.job_id IS NULL OR EXISTS (SELECT 1 FROM public.jobs p WHERE p.id = s.job_id))
    AND
    (s.squad_id IS NULL OR EXISTS (SELECT 1 FROM public.squads p WHERE p.id = s.squad_id));

WITH ins AS (
  INSERT INTO public.job_applications SELECT * FROM ok_job_applications ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'job_applications',
       (SELECT count(*) FROM stg_job_applications),
       (SELECT count(*) FROM ok_job_applications),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_job_applications) - (SELECT count(*) FROM ok_job_applications),
       (SELECT count(*) FROM ok_job_applications) - (SELECT count(*) FROM ins);

-- soft check: job_applications rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'job_applications', c.col, c.n FROM (
  SELECT 'applicant_id'::text AS col, count(*)::int AS n FROM public.job_applications x
    WHERE x.applicant_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.applicant_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- posts
CREATE TEMP TABLE stg_posts (LIKE public.posts INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_posts FROM 'migration-data/posts.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_posts ON COMMIT DROP AS
  SELECT s.* FROM stg_posts s
  WHERE
    (s.author_id IS NULL OR EXISTS (SELECT 1 FROM auth.users p WHERE p.id = s.author_id));

WITH ins AS (
  INSERT INTO public.posts SELECT * FROM ok_posts ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'posts',
       (SELECT count(*) FROM stg_posts),
       (SELECT count(*) FROM ok_posts),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_posts) - (SELECT count(*) FROM ok_posts),
       (SELECT count(*) FROM ok_posts) - (SELECT count(*) FROM ins);

-- soft check: posts rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'posts', c.col, c.n FROM (
  SELECT 'author_id'::text AS col, count(*)::int AS n FROM public.posts x
    WHERE x.author_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.author_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- post_likes
CREATE TEMP TABLE stg_post_likes (LIKE public.post_likes INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_post_likes FROM 'migration-data/post_likes.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_post_likes ON COMMIT DROP AS
  SELECT s.* FROM stg_post_likes s;

WITH ins AS (
  INSERT INTO public.post_likes SELECT * FROM ok_post_likes ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'post_likes',
       (SELECT count(*) FROM stg_post_likes),
       (SELECT count(*) FROM ok_post_likes),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_post_likes) - (SELECT count(*) FROM ok_post_likes),
       (SELECT count(*) FROM ok_post_likes) - (SELECT count(*) FROM ins);

-- soft check: post_likes rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'post_likes', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.post_likes x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- post_comments
CREATE TEMP TABLE stg_post_comments (LIKE public.post_comments INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_post_comments FROM 'migration-data/post_comments.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_post_comments ON COMMIT DROP AS
  SELECT s.* FROM stg_post_comments s;

WITH ins AS (
  INSERT INTO public.post_comments SELECT * FROM ok_post_comments ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'post_comments',
       (SELECT count(*) FROM stg_post_comments),
       (SELECT count(*) FROM ok_post_comments),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_post_comments) - (SELECT count(*) FROM ok_post_comments),
       (SELECT count(*) FROM ok_post_comments) - (SELECT count(*) FROM ins);

-- soft check: post_comments rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'post_comments', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.post_comments x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- post_saves
CREATE TEMP TABLE stg_post_saves (LIKE public.post_saves INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_post_saves FROM 'migration-data/post_saves.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_post_saves ON COMMIT DROP AS
  SELECT s.* FROM stg_post_saves s;

WITH ins AS (
  INSERT INTO public.post_saves SELECT * FROM ok_post_saves ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'post_saves',
       (SELECT count(*) FROM stg_post_saves),
       (SELECT count(*) FROM ok_post_saves),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_post_saves) - (SELECT count(*) FROM ok_post_saves),
       (SELECT count(*) FROM ok_post_saves) - (SELECT count(*) FROM ins);

-- soft check: post_saves rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'post_saves', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.post_saves x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- portfolios
CREATE TEMP TABLE stg_portfolios (LIKE public.portfolios INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_portfolios FROM 'migration-data/portfolios.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_portfolios ON COMMIT DROP AS
  SELECT s.* FROM stg_portfolios s;

WITH ins AS (
  INSERT INTO public.portfolios SELECT * FROM ok_portfolios ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'portfolios',
       (SELECT count(*) FROM stg_portfolios),
       (SELECT count(*) FROM ok_portfolios),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_portfolios) - (SELECT count(*) FROM ok_portfolios),
       (SELECT count(*) FROM ok_portfolios) - (SELECT count(*) FROM ins);

-- soft check: portfolios rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'portfolios', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.portfolios x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- stories
CREATE TEMP TABLE stg_stories (LIKE public.stories INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_stories FROM 'migration-data/stories.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_stories ON COMMIT DROP AS
  SELECT s.* FROM stg_stories s
  WHERE
    (s.user_id IS NULL OR EXISTS (SELECT 1 FROM auth.users p WHERE p.id = s.user_id));

WITH ins AS (
  INSERT INTO public.stories SELECT * FROM ok_stories ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'stories',
       (SELECT count(*) FROM stg_stories),
       (SELECT count(*) FROM ok_stories),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_stories) - (SELECT count(*) FROM ok_stories),
       (SELECT count(*) FROM ok_stories) - (SELECT count(*) FROM ins);

-- soft check: stories rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'stories', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.stories x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- story_views
CREATE TEMP TABLE stg_story_views (LIKE public.story_views INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_story_views FROM 'migration-data/story_views.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_story_views ON COMMIT DROP AS
  SELECT s.* FROM stg_story_views s
  WHERE
    (s.story_id IS NULL OR EXISTS (SELECT 1 FROM public.stories p WHERE p.id = s.story_id))
    AND
    (s.viewer_id IS NULL OR EXISTS (SELECT 1 FROM auth.users p WHERE p.id = s.viewer_id));

WITH ins AS (
  INSERT INTO public.story_views SELECT * FROM ok_story_views ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'story_views',
       (SELECT count(*) FROM stg_story_views),
       (SELECT count(*) FROM ok_story_views),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_story_views) - (SELECT count(*) FROM ok_story_views),
       (SELECT count(*) FROM ok_story_views) - (SELECT count(*) FROM ins);

-- soft check: story_views rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'story_views', c.col, c.n FROM (
  SELECT 'viewer_id'::text AS col, count(*)::int AS n FROM public.story_views x
    WHERE x.viewer_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.viewer_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- messages
CREATE TEMP TABLE stg_messages (LIKE public.messages INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_messages FROM 'migration-data/messages.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_messages ON COMMIT DROP AS
  SELECT s.* FROM stg_messages s
  WHERE
    (s.conversation_id IS NULL OR EXISTS (SELECT 1 FROM public.conversations p WHERE p.id = s.conversation_id))
    AND
    (s.sender_id IS NULL OR EXISTS (SELECT 1 FROM auth.users p WHERE p.id = s.sender_id));
UPDATE ok_messages SET reply_to = NULL;  -- self-reference restored below

WITH ins AS (
  INSERT INTO public.messages SELECT * FROM ok_messages ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'messages',
       (SELECT count(*) FROM stg_messages),
       (SELECT count(*) FROM ok_messages),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_messages) - (SELECT count(*) FROM ok_messages),
       (SELECT count(*) FROM ok_messages) - (SELECT count(*) FROM ins);

-- restore messages.reply_to now that all rows exist
UPDATE public.messages t
   SET reply_to = s.reply_to
  FROM stg_messages s
 WHERE t.id = s.id
   AND s.reply_to IS NOT NULL
   AND EXISTS (SELECT 1 FROM public.messages p WHERE p.id = s.reply_to);

-- soft check: messages rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'messages', c.col, c.n FROM (
  SELECT 'sender_id'::text AS col, count(*)::int AS n FROM public.messages x
    WHERE x.sender_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.sender_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- message_reactions
CREATE TEMP TABLE stg_message_reactions (LIKE public.message_reactions INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_message_reactions FROM 'migration-data/message_reactions.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_message_reactions ON COMMIT DROP AS
  SELECT s.* FROM stg_message_reactions s
  WHERE
    (s.message_id IS NULL OR EXISTS (SELECT 1 FROM public.messages p WHERE p.id = s.message_id))
    AND
    (s.user_id IS NULL OR EXISTS (SELECT 1 FROM auth.users p WHERE p.id = s.user_id));

WITH ins AS (
  INSERT INTO public.message_reactions SELECT * FROM ok_message_reactions ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'message_reactions',
       (SELECT count(*) FROM stg_message_reactions),
       (SELECT count(*) FROM ok_message_reactions),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_message_reactions) - (SELECT count(*) FROM ok_message_reactions),
       (SELECT count(*) FROM ok_message_reactions) - (SELECT count(*) FROM ins);

-- soft check: message_reactions rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'message_reactions', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.message_reactions x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- typing_status
CREATE TEMP TABLE stg_typing_status (LIKE public.typing_status INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_typing_status FROM 'migration-data/typing_status.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_typing_status ON COMMIT DROP AS
  SELECT s.* FROM stg_typing_status s
  WHERE
    (s.conversation_id IS NULL OR EXISTS (SELECT 1 FROM public.conversations p WHERE p.id = s.conversation_id))
    AND
    (s.user_id IS NULL OR EXISTS (SELECT 1 FROM auth.users p WHERE p.id = s.user_id));

WITH ins AS (
  INSERT INTO public.typing_status SELECT * FROM ok_typing_status ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'typing_status',
       (SELECT count(*) FROM stg_typing_status),
       (SELECT count(*) FROM ok_typing_status),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_typing_status) - (SELECT count(*) FROM ok_typing_status),
       (SELECT count(*) FROM ok_typing_status) - (SELECT count(*) FROM ins);

-- soft check: typing_status rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'typing_status', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.typing_status x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- creator_requests
CREATE TEMP TABLE stg_creator_requests (LIKE public.creator_requests INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_creator_requests FROM 'migration-data/creator_requests.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_creator_requests ON COMMIT DROP AS
  SELECT s.* FROM stg_creator_requests s;

WITH ins AS (
  INSERT INTO public.creator_requests SELECT * FROM ok_creator_requests ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'creator_requests',
       (SELECT count(*) FROM stg_creator_requests),
       (SELECT count(*) FROM ok_creator_requests),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_creator_requests) - (SELECT count(*) FROM ok_creator_requests),
       (SELECT count(*) FROM ok_creator_requests) - (SELECT count(*) FROM ins);

-- soft check: creator_requests rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'creator_requests', c.col, c.n FROM (
  SELECT 'client_id'::text AS col, count(*)::int AS n FROM public.creator_requests x
    WHERE x.client_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.client_id)
  UNION ALL
  SELECT 'creator_id'::text AS col, count(*)::int AS n FROM public.creator_requests x
    WHERE x.creator_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.creator_id)
) c WHERE c.n > 0;

-- ---------------------------------------------------------------- notifications
CREATE TEMP TABLE stg_notifications (LIKE public.notifications INCLUDING DEFAULTS) ON COMMIT DROP;
\copy stg_notifications FROM 'migration-data/notifications.csv' WITH (FORMAT csv, HEADER true)

CREATE TEMP TABLE ok_notifications ON COMMIT DROP AS
  SELECT s.* FROM stg_notifications s;

WITH ins AS (
  INSERT INTO public.notifications SELECT * FROM ok_notifications ON CONFLICT DO NOTHING RETURNING 1
)
INSERT INTO public._migration_report
  (table_name, csv_rows, importable_rows, inserted, skipped_orphan, skipped_conflict)
SELECT 'notifications',
       (SELECT count(*) FROM stg_notifications),
       (SELECT count(*) FROM ok_notifications),
       (SELECT count(*) FROM ins),
       (SELECT count(*) FROM stg_notifications) - (SELECT count(*) FROM ok_notifications),
       (SELECT count(*) FROM ok_notifications) - (SELECT count(*) FROM ins);

-- soft check: notifications rows pointing at a user id that has no auth account
INSERT INTO public._migration_orphans (table_name, column_name, missing_count)
SELECT 'notifications', c.col, c.n FROM (
  SELECT 'user_id'::text AS col, count(*)::int AS n FROM public.notifications x
    WHERE x.user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.user_id)
  UNION ALL
  SELECT 'actor_id'::text AS col, count(*)::int AS n FROM public.notifications x
    WHERE x.actor_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = x.actor_id)
) c WHERE c.n > 0;

SET session_replication_role = origin;
COMMIT;

\echo ''
\echo '=== IMPORT REPORT ==='
SELECT table_name, csv_rows, inserted, skipped_orphan, skipped_conflict
  FROM public._migration_report ORDER BY table_name;
\echo ''
\echo '=== DANGLING USER REFERENCES (expected > 0 only if you skipped auth import) ==='
SELECT * FROM public._migration_orphans ORDER BY table_name, column_name;
