/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppCreateRouteImport } from './routes/_authenticated/_app.create'
import { Route as AuthenticatedAppExploreRouteImport } from './routes/_authenticated/_app.explore'
import { Route as AuthenticatedAppHomeRouteImport } from './routes/_authenticated/_app.home'
import { Route as AuthenticatedAppJobsRouteImport } from './routes/_authenticated/_app.jobs'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/_app.messages'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/_app.notifications'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/_app.profile'
import { Route as AuthenticatedAppReelsRouteImport } from './routes/_authenticated/_app.reels'
import { Route as AuthenticatedAppSquadsRouteImport } from './routes/_authenticated/_app.squads'
import { Route as AuthenticatedOnboardingClientRouteImport } from './routes/_authenticated/onboarding/client'
import { Route as AuthenticatedOnboardingRoleRouteImport } from './routes/_authenticated/onboarding/role'
import { Route as AuthenticatedOnboardingSpecialtyRouteImport } from './routes/_authenticated/onboarding/specialty'
import { Route as AuthenticatedAppConnectionsUsernameRouteImport } from './routes/_authenticated/_app.connections.$username'
import { Route as AuthenticatedAppSquadsSquadIdRouteImport } from './routes/_authenticated/_app.squads.$squadId'
import { Route as AuthenticatedAppUserUsernameRouteImport } from './routes/_authenticated/_app.user.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppCreateRoute = AuthenticatedAppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppExploreRoute = AuthenticatedAppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHomeRoute = AuthenticatedAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppJobsRoute = AuthenticatedAppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReelsRoute = AuthenticatedAppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSquadsRoute = AuthenticatedAppSquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedOnboardingClientRoute =
  AuthenticatedOnboardingClientRouteImport.update({
    id: '/onboarding/client',
    path: '/onboarding/client',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoleRoute =
  AuthenticatedOnboardingRoleRouteImport.update({
    id: '/onboarding/role',
    path: '/onboarding/role',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingSpecialtyRoute =
  AuthenticatedOnboardingSpecialtyRouteImport.update({
    id: '/onboarding/specialty',
    path: '/onboarding/specialty',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppConnectionsUsernameRoute =
  AuthenticatedAppConnectionsUsernameRouteImport.update({
    id: '/connections/$username',
    path: '/connections/$username',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSquadsSquadIdRoute =
  AuthenticatedAppSquadsSquadIdRouteImport.update({
    id: '/$squadId',
    path: '/$squadId',
    getParentRoute: () => AuthenticatedAppSquadsRoute,
  } as any)
const AuthenticatedAppUserUsernameRoute =
  AuthenticatedAppUserUsernameRouteImport.update({
    id: '/user/$username',
    path: '/user/$username',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/create': typeof AuthenticatedAppCreateRoute
  '/explore': typeof AuthenticatedAppExploreRoute
  '/home': typeof AuthenticatedAppHomeRoute
  '/jobs': typeof AuthenticatedAppJobsRoute
  '/messages': typeof AuthenticatedAppMessagesRoute
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/reels': typeof AuthenticatedAppReelsRoute
  '/squads': typeof AuthenticatedAppSquadsRouteWithChildren
  '/onboarding/client': typeof AuthenticatedOnboardingClientRoute
  '/onboarding/role': typeof AuthenticatedOnboardingRoleRoute
  '/onboarding/specialty': typeof AuthenticatedOnboardingSpecialtyRoute
  '/connections/$username': typeof AuthenticatedAppConnectionsUsernameRoute
  '/squads/$squadId': typeof AuthenticatedAppSquadsSquadIdRoute
  '/user/$username': typeof AuthenticatedAppUserUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/create': typeof AuthenticatedAppCreateRoute
  '/explore': typeof AuthenticatedAppExploreRoute
  '/home': typeof AuthenticatedAppHomeRoute
  '/jobs': typeof AuthenticatedAppJobsRoute
  '/messages': typeof AuthenticatedAppMessagesRoute
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/reels': typeof AuthenticatedAppReelsRoute
  '/squads': typeof AuthenticatedAppSquadsRouteWithChildren
  '/onboarding/client': typeof AuthenticatedOnboardingClientRoute
  '/onboarding/role': typeof AuthenticatedOnboardingRoleRoute
  '/onboarding/specialty': typeof AuthenticatedOnboardingSpecialtyRoute
  '/connections/$username': typeof AuthenticatedAppConnectionsUsernameRoute
  '/squads/$squadId': typeof AuthenticatedAppSquadsSquadIdRoute
  '/user/$username': typeof AuthenticatedAppUserUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_app/create': typeof AuthenticatedAppCreateRoute
  '/_authenticated/_app/explore': typeof AuthenticatedAppExploreRoute
  '/_authenticated/_app/home': typeof AuthenticatedAppHomeRoute
  '/_authenticated/_app/jobs': typeof AuthenticatedAppJobsRoute
  '/_authenticated/_app/messages': typeof AuthenticatedAppMessagesRoute
  '/_authenticated/_app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/_app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/_app/reels': typeof AuthenticatedAppReelsRoute
  '/_authenticated/_app/squads': typeof AuthenticatedAppSquadsRouteWithChildren
  '/_authenticated/onboarding/client': typeof AuthenticatedOnboardingClientRoute
  '/_authenticated/onboarding/role': typeof AuthenticatedOnboardingRoleRoute
  '/_authenticated/onboarding/specialty': typeof AuthenticatedOnboardingSpecialtyRoute
  '/_authenticated/_app/connections/$username': typeof AuthenticatedAppConnectionsUsernameRoute
  '/_authenticated/_app/squads/$squadId': typeof AuthenticatedAppSquadsSquadIdRoute
  '/_authenticated/_app/user/$username': typeof AuthenticatedAppUserUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/splash'
    | '/create'
    | '/explore'
    | '/home'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/reels'
    | '/squads'
    | '/onboarding/client'
    | '/onboarding/role'
    | '/onboarding/specialty'
    | '/connections/$username'
    | '/squads/$squadId'
    | '/user/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/splash'
    | '/create'
    | '/explore'
    | '/home'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/reels'
    | '/squads'
    | '/onboarding/client'
    | '/onboarding/role'
    | '/onboarding/specialty'
    | '/connections/$username'
    | '/squads/$squadId'
    | '/user/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/splash'
    | '/_authenticated/_app'
    | '/_authenticated/_app/create'
    | '/_authenticated/_app/explore'
    | '/_authenticated/_app/home'
    | '/_authenticated/_app/jobs'
    | '/_authenticated/_app/messages'
    | '/_authenticated/_app/notifications'
    | '/_authenticated/_app/profile'
    | '/_authenticated/_app/reels'
    | '/_authenticated/_app/squads'
    | '/_authenticated/onboarding/client'
    | '/_authenticated/onboarding/role'
    | '/_authenticated/onboarding/specialty'
    | '/_authenticated/_app/connections/$username'
    | '/_authenticated/_app/squads/$squadId'
    | '/_authenticated/_app/user/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SplashRoute: typeof SplashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/create': {
      id: '/_authenticated/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedAppCreateRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/explore': {
      id: '/_authenticated/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedAppExploreRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/home': {
      id: '/_authenticated/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedAppHomeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/jobs': {
      id: '/_authenticated/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedAppJobsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/messages': {
      id: '/_authenticated/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/notifications': {
      id: '/_authenticated/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profile': {
      id: '/_authenticated/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/reels': {
      id: '/_authenticated/_app/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedAppReelsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/squads': {
      id: '/_authenticated/_app/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof AuthenticatedAppSquadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/onboarding/client': {
      id: '/_authenticated/onboarding/client'
      path: '/onboarding/client'
      fullPath: '/onboarding/client'
      preLoaderRoute: typeof AuthenticatedOnboardingClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/role': {
      id: '/_authenticated/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof AuthenticatedOnboardingRoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/specialty': {
      id: '/_authenticated/onboarding/specialty'
      path: '/onboarding/specialty'
      fullPath: '/onboarding/specialty'
      preLoaderRoute: typeof AuthenticatedOnboardingSpecialtyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/connections/$username': {
      id: '/_authenticated/_app/connections/$username'
      path: '/connections/$username'
      fullPath: '/connections/$username'
      preLoaderRoute: typeof AuthenticatedAppConnectionsUsernameRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/squads/$squadId': {
      id: '/_authenticated/_app/squads/$squadId'
      path: '/$squadId'
      fullPath: '/squads/$squadId'
      preLoaderRoute: typeof AuthenticatedAppSquadsSquadIdRouteImport
      parentRoute: typeof AuthenticatedAppSquadsRoute
    }
    '/_authenticated/_app/user/$username': {
      id: '/_authenticated/_app/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof AuthenticatedAppUserUsernameRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppSquadsRouteChildren {
  AuthenticatedAppSquadsSquadIdRoute: typeof AuthenticatedAppSquadsSquadIdRoute
}

const AuthenticatedAppSquadsRouteChildren: AuthenticatedAppSquadsRouteChildren =
  {
    AuthenticatedAppSquadsSquadIdRoute: AuthenticatedAppSquadsSquadIdRoute,
  }

const AuthenticatedAppSquadsRouteWithChildren =
  AuthenticatedAppSquadsRoute._addFileChildren(
    AuthenticatedAppSquadsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCreateRoute: typeof AuthenticatedAppCreateRoute
  AuthenticatedAppExploreRoute: typeof AuthenticatedAppExploreRoute
  AuthenticatedAppHomeRoute: typeof AuthenticatedAppHomeRoute
  AuthenticatedAppJobsRoute: typeof AuthenticatedAppJobsRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppReelsRoute: typeof AuthenticatedAppReelsRoute
  AuthenticatedAppSquadsRoute: typeof AuthenticatedAppSquadsRouteWithChildren
  AuthenticatedAppConnectionsUsernameRoute: typeof AuthenticatedAppConnectionsUsernameRoute
  AuthenticatedAppUserUsernameRoute: typeof AuthenticatedAppUserUsernameRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCreateRoute: AuthenticatedAppCreateRoute,
  AuthenticatedAppExploreRoute: AuthenticatedAppExploreRoute,
  AuthenticatedAppHomeRoute: AuthenticatedAppHomeRoute,
  AuthenticatedAppJobsRoute: AuthenticatedAppJobsRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppReelsRoute: AuthenticatedAppReelsRoute,
  AuthenticatedAppSquadsRoute: AuthenticatedAppSquadsRouteWithChildren,
  AuthenticatedAppConnectionsUsernameRoute:
    AuthenticatedAppConnectionsUsernameRoute,
  AuthenticatedAppUserUsernameRoute: AuthenticatedAppUserUsernameRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingClientRoute: typeof AuthenticatedOnboardingClientRoute
  AuthenticatedOnboardingRoleRoute: typeof AuthenticatedOnboardingRoleRoute
  AuthenticatedOnboardingSpecialtyRoute: typeof AuthenticatedOnboardingSpecialtyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingClientRoute: AuthenticatedOnboardingClientRoute,
  AuthenticatedOnboardingRoleRoute: AuthenticatedOnboardingRoleRoute,
  AuthenticatedOnboardingSpecialtyRoute: AuthenticatedOnboardingSpecialtyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SplashRoute: SplashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
