// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Active production fallback values
const DEFAULT_SUPABASE_URL = "https://mouvlzrsaxhczywkrwyq.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_nBxswRGxXCgpKQZLw2sZvA_ZZeNFuDn";
const DEPRECATED_PROJECT_REF = "njgfixexgkflpmojmzao";

function createSupabaseClient() {
  // Check client-side Vite variables first, then server-side process.env
  let SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    (typeof process !== 'undefined' ? (process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL) : undefined);

  let SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    (typeof process !== 'undefined'
      ? (process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
         process.env.VITE_SUPABASE_ANON_KEY ||
         process.env.SUPABASE_PUBLISHABLE_KEY ||
         process.env.SUPABASE_ANON_KEY)
      : undefined);

  // Safeguard: Automatically redirect if stale deprecated project reference is found
  if (SUPABASE_URL && SUPABASE_URL.includes(DEPRECATED_PROJECT_REF)) {
    console.warn(`[Supabase Client] Stale project ref ${DEPRECATED_PROJECT_REF} detected. Redirecting to active production project.`);
    SUPABASE_URL = DEFAULT_SUPABASE_URL;
    SUPABASE_PUBLISHABLE_KEY = DEFAULT_SUPABASE_PUBLISHABLE_KEY;
  }

  // Resilient fallback to active production project
  if (!SUPABASE_URL) SUPABASE_URL = DEFAULT_SUPABASE_URL;
  if (!SUPABASE_PUBLISHABLE_KEY) SUPABASE_PUBLISHABLE_KEY = DEFAULT_SUPABASE_PUBLISHABLE_KEY;

  SUPABASE_URL = SUPABASE_URL.trim().replace(/\/+$/, '');
  SUPABASE_PUBLISHABLE_KEY = SUPABASE_PUBLISHABLE_KEY.trim();

  // Diagnostics for deployment verification
  console.log(`[Supabase Client] Connected to: ${SUPABASE_URL}`);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      _supabase = createSupabaseClient();
      if (typeof window !== 'undefined') {
        (window as any).__supabase = _supabase;
      }
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});
if (typeof window !== 'undefined') {
  (window as any).__supabase = supabase;
}

